### ISSUE TITLE
Create POST/PUT a UserStopProgress

### ISSUE THREAD

**Issue by SabrinaFZ** [BRIKEV/wandtrek-app#38]
We need to create/update the progress of a stop for an user

Endpoint: POST/PUT `users/:id/stops/:id/progress`

**Comment by SabrinaFZ** [comment]
@kevinccbsg Should be the endpoint like that?

**Comment by kevinccbsg** [comment]
No, more like this comment

https://github.com/BRIKEV/wandtrek-app/issues/33#issuecomment-1290972346
